Keep SSH keys with config

diff --git a/bin/rhls-lab b/bin/rhls-lab
--- a/bin/rhls-lab
+++ b/bin/rhls-lab
@@ -7,12 +7,12 @@ COMMAND_NAME=rhls-lab
 CONFIG_DIRECTORY=~/.config
 DEFAULT_PROFILE_NAME=default
 RHLS_LAB_CONFIG_DIRECTORY="${CONFIG_DIRECTORY}/rhls-lab"
-RHLS_LAB_CONFIG_FILE_EXTENSION=.config
-RHLS_LAB_CONFIG_FILENAME=config
 PATH_TO_DEFAULT_CONFIG="${RHLS_LAB_CONFIG_DIRECTORY}/${DEFAULT_PROFILE_NAME}"
+RHLS_LAB_CONFIG_FILENAME=config
+RHLS_LAB_SSH_KEY_FILENAME=id.rsa
 
 display_help() {
-  echo "Usage: $COMMAND_NAME {init|connect|profile}" >&2
+  echo "Usage: $COMMAND_NAME {init|connect|profile|add-key}" >&2
   exit 1
 }
 
@@ -34,6 +34,7 @@ connect() {
   echo "Connecting to lab for profile '${profile}'"
 
   path_to_config="${RHLS_LAB_CONFIG_DIRECTORY}/${profile}/${RHLS_LAB_CONFIG_FILENAME}"
+  path_to_key="${RHLS_LAB_CONFIG_DIRECTORY}/${profile}/${RHLS_LAB_SSH_KEY_FILENAME}"
 
   if [ ! -f "$path_to_config" ]; then
    echo "No config detected for profile '${profile}'. Initialise config file by running: $COMMAND_NAME init"
@@ -42,8 +43,8 @@ connect() {
 
   . $path_to_config
 
-  ssh-add ~/.ssh/rht_classroom.rsa
-  ssh -i ~/.ssh/rht_classroom.rsa -J cloud-user@$RHLS_PUBLIC_IP:$RHLS_PUBLIC_PORT $RHLS_USERNAME@$RHLS_LOCAL_IP -p $RHLS_LOCAL_PORT
+  ssh-add "$path_to_key"
+  ssh -i "$path_to_key" -J cloud-user@$RHLS_PUBLIC_IP:$RHLS_PUBLIC_PORT $RHLS_USERNAME@$RHLS_LOCAL_IP -p $RHLS_LOCAL_PORT
 }
 
 init() {
@@ -83,10 +84,15 @@ init() {
   read -p "Enter Local Port [53009]: " local_port_input_raw
   local_port_input=${local_port_input_raw:-53009}
 
+  read -p "Enter path to SSH Key: [~/Downloads/rht_classroom.rsa]" path_to_key_input_raw
+  path_to_key_input=${path_to_key_input_raw:"~/Downloads/rht_classroom.rsa"}
+
   echo "Saving configuration to $RHLS_LAB_CONFIG_DIRECTORY/$profile_name_input/$RHLS_LAB_CONFIG_FILENAME"
   mkdir -p "$RHLS_LAB_CONFIG_DIRECTORY/$profile_name_input"
   echo -e "#$profile_name_input\nRHLS_PUBLIC_IP=$public_ip_input\nRHLS_PUBLIC_PORT=$public_port_input\nRHLS_USERNAME=$username_input\nRHLS_LOCAL_IP=$local_ip_input\nRHLS_LOCAL_PORT=$local_port_input" \
   > "$RHLS_LAB_CONFIG_DIRECTORY/$profile_name_input/$RHLS_LAB_CONFIG_FILENAME"
+
+  configure_ssh_key -p "$profile_name_input" -k "$path_to_key_input"
 
   if [ -e "$PATH_TO_DEFAULT_CONFIG" ]; then
     read -p "Make this your default profile? (y/n) [y] " make_default
@@ -97,6 +103,39 @@ init() {
   fi
 
   echo "Initialisation complete"
+}
+
+configure_ssh_key() {
+
+  local OPTIND profile path_to_key
+  profile=$DEFAULT_PROFILE_NAME
+
+  while getopts ":k:p:" option; do
+    case "$option" in
+    p)  profile=$(echo -n "$OPTARG" | xargs)
+        ;;
+    k)  path_to_key=$(echo -n "$OPTARG" | xargs)
+        ;;
+    \?) printf "Unrecognised option: -%s\n" "$OPTARG" >&2
+        exit 1
+        ;;
+    esac
+  done
+  shift $((OPTIND - 1))
+
+  if [ -z "$path_to_key" ]; then
+    echo "Must provide path to SSH key"
+    exit 1
+  elif [ ! -f "$path_to_key" ]; then
+    echo "File not found at path '${path_to_key}'"
+    exit 1
+  fi
+
+  path_to_profile_config="${RHLS_LAB_CONFIG_DIRECTORY}/${profile}"
+
+  mv "$path_to_key" "$path_to_profile_config/$RHLS_LAB_SSH_KEY_FILENAME"
+
+  chmod 0600 "$path_to_profile_config/$RHLS_LAB_SSH_KEY_FILENAME"
 }
 
 make_profile_default() {
@@ -128,6 +167,9 @@ case "$1" in
     ;;
   profile)
     make_profile_default "${2}"
+    ;;
+  add-key)
+    configure_ssh_key "${@:2}"
     ;;
   *)
     display_help
