Add support for multiple profiles

diff --git a/bin/rhls-lab b/bin/rhls-lab
--- a/bin/rhls-lab
+++ b/bin/rhls-lab
@@ -4,77 +4,133 @@
 
 # global vars
 COMMAND_NAME=rhls-lab
-RHLS_LAB_CONFIG_FILENAME=rhls-lab.config
 CONFIG_DIRECTORY=~/.config
-PATH_TO_RHLS_LAB_CONFIG_FILE="${CONFIG_DIRECTORY}/${RHLS_LAB_CONFIG_FILENAME}"
+DEFAULT_PROFILE_NAME=default
+RHLS_LAB_CONFIG_DIRECTORY="${CONFIG_DIRECTORY}/rhls-lab"
+RHLS_LAB_CONFIG_FILE_EXTENSION=.config
+PATH_TO_DEFAULT_CONFIG="${RHLS_LAB_CONFIG_DIRECTORY}/${DEFAULT_PROFILE_NAME}${RHLS_LAB_CONFIG_FILE_EXTENSION}"
 
 display_help() {
- echo "Usage: $COMMAND_NAME {init|connect}" >&2
- exit 1
+  echo "Usage: $COMMAND_NAME {init|connect|profile}" >&2
+  exit 1
 }
 
 connect() {
- echo "Reading config from file"
- if [ ! -f $PATH_TO_RHLS_LAB_CONFIG_FILE ]; then
-  echo "No config detected. Initialise config file by running: $COMMAND_NAME init"
-  exit 1
- fi
- . $PATH_TO_RHLS_LAB_CONFIG_FILE
+  local OPTIND profile
+  profile=$DEFAULT_PROFILE_NAME
 
- echo "Connecting to RHLS Lab Environment"
+  while getopts ":p:" option; do
+    case "$option" in
+    p)  profile=$(echo -n "$OPTARG" | xargs)
+        ;;
+    \?) printf "Unrecognised option: -%s\n" "$OPTARG" >&2
+        exit 1
+        ;;
+    esac
+  done
+  shift $((OPTIND - 1))
 
- if [ -z "$1" ]
- then
-   read -p "Enter Public IP address [RHLS_PUBLIC_IP]: " public_ip_input
-   connect_to_lab_ip=${public_ip_input:-$RHLS_PUBLIC_IP}
- else
-   connect_to_lab_ip=$1
- fi
+  echo "Connecting to lab for profile '${profile}'"
 
- if [ -z "$connect_to_lab_ip" ]
- then
-   echo "Failed to detect lab IP"
+  path_to_config="${RHLS_LAB_CONFIG_DIRECTORY}/${profile}${RHLS_LAB_CONFIG_FILE_EXTENSION}"
+
+  if [ ! -f "$path_to_config" ]; then
+   echo "No config detected for profile '${profile}'. Initialise config file by running: $COMMAND_NAME init"
    exit 1
- fi
+  fi
 
- ssh-add ~/.ssh/rht_classroom.rsa
- ssh -i ~/.ssh/rht_classroom.rsa -J cloud-user@$connect_to_lab_ip:$RHLS_PUBLIC_PORT $RHLS_USERNAME@$RHLS_LOCAL_IP -p $RHLS_LOCAL_PORT
+  . $path_to_config
+
+  ssh-add ~/.ssh/rht_classroom.rsa
+  ssh -i ~/.ssh/rht_classroom.rsa -J cloud-user@$RHLS_PUBLIC_IP:$RHLS_PUBLIC_PORT $RHLS_USERNAME@$RHLS_LOCAL_IP -p $RHLS_LOCAL_PORT
 }
 
 init() {
- echo "Initialising RHLS Lab Environment configuration"
+  echo "Initialising RHLS Lab Environment configuration"
 
- read -p "Enter Public IP address: " public_ip_input
+  read -p "Enter Profile Name: " profile_name_input_raw
+  profile_name_input=$(echo -n "$profile_name_input_raw" | xargs)
 
- read -p "Enter Public Port [22022]: " public_port_input_raw
- public_port_input=${public_port_input_raw:-22022}
+  if [ -z "$profile_name_input" ]
+  then
+    echo "Profile Name is required and must not collide with reserved name '${DEFAULT_PROFILE_NAME}'"
+    exit 1
+  elif [ "$profile_name_input" = "$DEFAULT_PROFILE_NAME" ]
+  then
+    echo "Profile Name must not collide with reserved name '${DEFAULT_PROFILE_NAME}'"
+    exit 1
+  fi
 
- read -p "Enter Username [student]: " username_input_raw
- username_input=${username_input_raw:-"student"}
- 
- read -p "Enter Local IP address [172.25.252.1]: " local_ip_input_raw
- local_ip_input=${local_ip_input_raw:-"172.25.252.1"}
- 
- read -p "Enter Local Port [53009]: " local_port_input_raw
- local_port_input=${local_port_input_raw:-53009}
+  read -p "Enter Public IP address: " public_ip_input_raw
+  public_ip_input=$(echo -n "$public_ip_input_raw" | xargs)
 
- echo "Saving configuration to $PATH_TO_RHLS_LAB_CONFIG_FILE"
- mkdir -p $CONFIG_DIRECTORY
- echo -e "RHLS_PUBLIC_IP=$public_ip_input\nRHLS_PUBLIC_PORT=$public_port_input\nRHLS_USERNAME=$username_input\nRHLS_LOCAL_IP=$local_ip_input\nRHLS_LOCAL_PORT=$local_port_input" > $PATH_TO_RHLS_LAB_CONFIG_FILE
+  if [ -z "$public_ip_input" ]
+  then
+    echo "Public IP Address must be provided"
+    exit 1
+  fi
 
- echo "Initialisation complete"
+  read -p "Enter Public Port [22022]: " public_port_input_raw
+  public_port_input=${public_port_input_raw:-22022}
+
+  read -p "Enter Username [student]: " username_input_raw
+  username_input=${username_input_raw:-"student"}
+
+  read -p "Enter Local IP address [172.25.252.1]: " local_ip_input_raw
+  local_ip_input=${local_ip_input_raw:-"172.25.252.1"}
+
+  read -p "Enter Local Port [53009]: " local_port_input_raw
+  local_port_input=${local_port_input_raw:-53009}
+
+  echo "Saving configuration to $RHLS_LAB_CONFIG_DIRECTORY/$profile_name_input$RHLS_LAB_CONFIG_FILE_EXTENSION"
+  mkdir -p "$RHLS_LAB_CONFIG_DIRECTORY"
+  echo -e "#$profile_name_input\nRHLS_PUBLIC_IP=$public_ip_input\nRHLS_PUBLIC_PORT=$public_port_input\nRHLS_USERNAME=$username_input\nRHLS_LOCAL_IP=$local_ip_input\nRHLS_LOCAL_PORT=$local_port_input" \
+  > "$RHLS_LAB_CONFIG_DIRECTORY/$profile_name_input$RHLS_LAB_CONFIG_FILE_EXTENSION"
+
+  if [ -e "$PATH_TO_DEFAULT_CONFIG" ]; then
+    read -p "Make this your default profile? (y/n) [y] " make_default
+  fi
+
+  if [ ! -e "$PATH_TO_DEFAULT_CONFIG" ] || [ "$make_default" = "y" ]; then
+    make_profile_default "$profile_name_input"
+  fi
+
+  echo "Initialisation complete"
 }
 
+make_profile_default() {
+
+  profile="$1"
+  path_to_profile_config="${RHLS_LAB_CONFIG_DIRECTORY}/${profile}${RHLS_LAB_CONFIG_FILE_EXTENSION}"
+
+  if [ ! -f "$path_to_profile_config" ]; then
+    echo "Profile '${profile}' not found"
+    exit 1
+  fi
+
+  if [ -e "$PATH_TO_DEFAULT_CONFIG" ]; then
+   rm "$PATH_TO_DEFAULT_CONFIG"
+  fi
+
+  ln -s "$path_to_profile_config" "$PATH_TO_DEFAULT_CONFIG"
+
+  echo "Default profile has been set to '${profile}'"
+}
+
+# Main
 case "$1" in
- init)
-  init
-  ;;
- connect)
-  connect
-  ;;
- *)
-  display_help
-  ;;
+  init)
+    init
+    ;;
+  connect)
+    connect "${@:2}"
+    ;;
+  profile)
+    make_profile_default "${2}"
+    ;;
+  *)
+    display_help
+    ;;
 esac
 
 exit 0
